# Oyunun dilleri: Türkçe (asıl dil) ve İngilizce. Kodda yazılar Türkçe yazılır; ekrana çizilirken score.draw_text
# kendisi t() ile çevirir. Kurallar:
# - Sabit yazı olduğu gibi draw_text'e verilir: draw_text(screen, font, "Geri", ...)
# - Sayı içeren yazı kalıptan kurulur: t("Rekor: {} m").format(n). f-string ile kurulan yazı çevrilemez
#   (check_lang.py yakalar). İngilizcede tekil/çoğul farkı olan kalıpta değer (tekil, çoğul) ikilisidir: t("{} elmas", n)
# - Bir değişkende saklanıp sonra çizilen yazı mark("...") ile işaretlenir (çevirisi çizilirken olur; mark sadece
#   check_lang.py'nin onu bulması için). Bölüm ve skin adları gibi büyük listeleri check_lang.py kendisi tarar.
# İngilizcesi EN sözlüğünde; çevirisi yoksa yazı Türkçe kalır. Yeni yazı eklenince EN'e de ekle:
# python check_lang.py eksikleri söyler (GitHub'da yayından önce de çalışır, eksik varsa yayına çıkmaz).
import locale

LANGUAGES = {"tr": "Türkçe", "en": "English"}  # ayarlar ekranında bu sırayla değişir
DEFAULT_LANGUAGE = "en"  # cihazın dili Türkçe değilse
_current = ["tr"]


def set_language(code):
    _current[0] = code if code in LANGUAGES else DEFAULT_LANGUAGE


def language():
    return _current[0]


def device_language(web):
    # Telefonun / tarayıcının / bilgisayarın dili Türkçeyse "tr", değilse İngilizce (kayıtlı seçim yoksa bununla açılır)
    try:
        if web:
            from platform import window

            name = str(window.navigator.language)  # "tr-TR", "en-US"...
        else:
            name = locale.getlocale()[0] or ""  # "Turkish_Türkiye" (Windows), "tr_TR"...
    except Exception:
        name = ""
    name = name.lower()
    return "tr" if name.startswith(("tr", "turkish")) else DEFAULT_LANGUAGE


def mark(text):
    # Çevrilecek yazıyı işaretler (check_lang.py bulsun); yazı aynen döner, çevirisi çizilirken olur
    return text


def t(text, count=None):
    # Yazının seçili dildeki hâli; count = İngilizcede tekil/çoğul seçimi için sayı
    if _current[0] == "tr":
        return text
    value = EN.get(text, text)
    if isinstance(value, tuple):
        return value[0] if count == 1 else value[1]
    return value


# Türkçe yazı → İngilizcesi (tekil/çoğul farkı olanlarda ikili). Bölüm (stage) oyuncuya İngilizcede "Level"
EN = {
    # Menüler ve düğmeler
    "Oyna": "Play",
    "Karakterler": "Characters",
    "Ayarlar": "Settings",
    "Nasıl Oynanır": "How to Play",
    "Rekorlar": "Records",
    "Geri": "Back",
    "Devam Et": "Resume",
    "Ana Menü": "Main Menu",
    "Tekrar Oyna": "Play Again",
    "Tekrar Dene": "Try Again",
    "Bölümler": "Levels",
    "Sonsuz Oyun": "Endless",
    "Sonraki Bölüm": "Next Level",
    "Hayır": "No",
    "Ses: Kapalı": "Sound: Off",
    "Ses: Açık": "Sound: On",
    "Zorluk: {}": "Difficulty: {}",
    "Dil: {}": "Language: {}",
    "Tema: {}": "Theme: {}",
    "Nostalji": "Retro",
    "Modern": "Modern",
    "Müzik": "Music",
    "Efektler": "Effects",
    "%{}": "{}%",
    "Durdu": "Paused",
    "Kolay": "Easy",
    "Orta": "Normal",
    "Zor": "Hard",
    "Ultra Zor": "Ultra Hard",
    "Daha akıcı oyun için": "For smoother play,",
    "Düşük Güç Modu'nu kapat": "turn off Low Power Mode",
    "{} kare/sn": "{} FPS",
    # Giriş ekranı
    "Dokun ve Başla": "Tap to Start",
    "Tıkla ve Başla": "Click to Start",
    "Lavdan kaç, en yükseğe tırman!": "Escape the lava, climb to the top!",
    # Oyun sırasında ve oyun sonunda
    "Puan: {}": "Score: {}",
    "Altın: {}": "Coins: {}",
    "Elmas: {}": "Gems: {}",
    "Düşman: {}": "Enemies: {}",
    "YENİ REKOR!": "NEW RECORD!",
    "Rekor {} m": "Best {} m",
    "Rekor: {} m": "Best: {} m",
    "En yüksek puan: {}": "High score: {}",
    "Kaybettin!": "Game Over!",
    "Devam Et?": "Continue?",
    "Kaldığın yerden 1 canla": "Right where you were, with 1 life",
    "Bayrağa {} m kaldı!": "{} m to the flag!",
    "Rekora {} m kaldı!": "{} m to your best!",
    "Devam Et: {}": "Continue: {}",
    "Cüzdan: {}": "Wallet: {}",
    "Yeni karakter: {}!": "New character: {}!",
    "Yeni karakterler: {}!": "New characters: {}!",
    "{} yeni karakter açıldı!": "{} new characters unlocked!",
    "+{} elmas topladın": ("+{} gem found", "+{} gems found"),
    "+{} elmas: rekor ödülü": ("+{} gem: record reward", "+{} gems: record reward"),
    "+{} elmas: yıldız ödülü": ("+{} gem: star reward", "+{} gems: star reward"),
    "+{total} elmas: {found} toplandı + {bonus} rekor ödülü": "+{total} gems: {found} found + {bonus} record reward",
    "+{total} elmas: {found} toplandı + {bonus} yıldız ödülü": "+{total} gems: {found} found + {bonus} star reward",
    # Reklamlar
    "Reklam İzle": "Watch Ad",
    "Reklam yok": "No ad",
    "2 Kat: +{}": "Double: +{}",
    "+{} elmas alındı!": ("+{} gem added!", "+{} gems added!"),
    "+{} elmas!": ("+{} gem!", "+{} gems!"),
    "Şu an reklam yok, sonra tekrar dene": "No ad right now, try again later",
    "REKLAM": "AD",
    "Deneme reklamı (gerçek reklam değil)": "Test ad (not a real ad)",
    # Nasıl oynanır
    "Amaç: en yükseğe tırman, rekorunu geç!": "Goal: climb high, beat your best!",
    "Ok tuşları / A-D: yürü    Boşluk / W: zıpla": "Arrows / A-D: walk    Space / W: jump",
    "Telefonda: alttaki düğmeler": "On phones: the buttons at the bottom",
    "ESC / P: durdur    {}: ses": "ESC / P: pause    {}: sound",
    "Bayrak: bölümün sonu, ona ulaş!": "Flag: end of the level, reach it!",
    "Altın: +{points} puan, yeni renk al": "Coin: +{points} points, buy colors",
    "Elmas: nadir! Yeni karakter al": "Gem: rare! Buy new characters",
    "Kalp: +1 can": "Heart: +1 life",
    "Mıknatıs: altınları çeker": "Magnet: pulls in coins",
    "Kalkan: düşman ve lavdan korur": "Shield: guards from enemies, lava",
    "Yay: çok yükseğe fırlatır": "Spring: launches you up high",
    "Çatlak taş: basınca kırılır": "Cracked stone: breaks underfoot",
    "Düşman: üstüne zıpla, yanına değme": "Enemy: stomp it, avoid its sides",
    "Sümük: zıplar, inince üstüne bas": "Slime: hops, stomp it as it lands",
    "Kirpi: dikenli, üstüne BASMA!": "Hedgehog: spiky, DON'T stomp it!",
    "Topçu: ateş atar, üstüne zıpla": "Cannon: shoots fire, jump on it",
    "Yarasa: onun da üstüne zıpla": "Bat: jump on it too",
    "Arı: aşağı yukarı uçar": "Bee: flies up and down",
    "Lav: yükseliyor, acele et!": "Lava: it's rising, hurry!",
    "Golem: alevi sönünce kafasına bas": "Golem: stomp it when its fire is out",
    # Boss (Lav Golemi)
    "Lav Golemi": "Lava Golem",
    "Alevi sönünce kafasına bas!": "Stomp its head when the fire goes out!",
    "Golem yenildi!": "Golem defeated!",
    "Basamaklardan tırman!": "Climb the stairs!",
    # Rekorlar
    "Tırmanış": "Climb",
    "Puan": "Score",
    "Oynanan oyun": "Games played",
    "Toplam tırmanış": "Total climbed",
    "Toplam altın": "Total coins",
    "Yenilen düşman": "Enemies defeated",
    "Bölüm yıldızı": "Level stars",
    # Bölüm ekranları
    "{}. Bölüm: {}": "Level {}: {}",
    "{}. Bölüm ({})": "Level {} ({})",
    "Yıldızlar: {} / {}": "Stars: {} / {}",
    "Bölümler: her zorlukta {} bölüm, yıldız topla": "Levels: {} per difficulty, collect stars",
    "Sonsuz Oyun: rekor için tırman ({})": "Endless: climb for a record ({})",
    "Hedef: {} m": "Goal: {} m",
    "Lav var!": "Lava!",
    "Kilitli": "Locked",
    "Önceki bölümü bitirince açılır": "Finish the previous level to unlock",
    "Her zorluğun bölümleri ayrı": "Each difficulty has its own levels",
    "Tebrikler!": "Well Done!",
    "Bayrağa ulaştın": "Reached the flag",
    "Altın: {} / {}  (en az {})": "Coins: {} / {}  (at least {})",
    "Hiç can kaybetmeden": "Without losing a life",
    "Yeni bölüm açıldı!": "New level unlocked!",
    "{} bölümleri bitti!": "All {} levels done!",
    "Bayrağa {} m kalmıştı": "You were {} m from the flag",
    # Karakterler ekranı
    "Renkler": "Colors",
    "Efsanevi": "Legendary",
    "Şu an bunu giyiyorsun": "You're wearing this one",
    "Görevle açıldı!": "Unlocked by a quest!",
    "Senin": "Yours",
    "Seçili": "Selected",
    "Seç": "Select",
    "Satın Al: {}": "Buy: {}",
    "Fiyatı: {} altın": "Price: {} coins",
    "Fiyatı: {} elmas": "Price: {} gems",
    "Fiyatı: {price} altın ({need} altın daha topla)": (
        "Price: {price} coins (need {need} more coin)", "Price: {price} coins (need {need} more coins)"
    ),
    "Fiyatı: {price} elmas ({need} elmas daha topla)": (
        "Price: {price} gems (need {need} more gem)", "Price: {price} gems (need {need} more gems)"
    ),
    "{} oyun oyna": "Play {} games",
    "Toplam {} m tırman": "Climb {} m in total",
    "{} düşman yen": "Defeat {} enemies",
    "Toplam {} altın topla": "Collect {} coins in total",
    "Bölümlerden {} yıldız topla": "Earn {} stars in levels",
    "Sonsuz Oyun'da {} m tırman ({})": "Climb {} m in Endless ({})",
    # Skin adları
    "Klasik": "Classic",
    "Okyanus": "Ocean",
    "Nane": "Mint",
    "Şeker": "Candy",
    "Lavanta": "Lavender",
    "Kar": "Snow",
    "Gece": "Night",
    "Kaplan": "Tiger",
    "Çilek": "Strawberry",
    "Gökkuşağı": "Rainbow",
    "Altın": "Gold",
    "Kedi": "Cat",
    "Kurbağa": "Frog",
    "Penguen": "Penguin",
    "Panda": "Panda",
    "Tavşan": "Bunny",
    "Mantar": "Mushroom",
    "Kardan Adam": "Snowman",
    "Ahtapot": "Octopus",
    "Hayalet": "Ghost",
    "Uzaylı": "Alien",
    "Korsan": "Pirate",
    "Robot": "Robot",
    "Ninja": "Ninja",
    "Şövalye": "Knight",
    "Astronot": "Astronaut",
    "Şimşek": "Lightning",
    "Ejderha": "Dragon",
    "Kozmik": "Cosmic",
    "Tekboynuz": "Unicorn",
    "Kral": "King",
    "Buz": "Ice",
    "Gölge": "Shadow",
    # Bölüm adları ve tanıtımları (stages.py; aynı tanıtım birkaç bölümde geçebilir)
    "Merhaba!": "Hello!",
    "Yürü, zıpla, bayrağa ulaş!": "Walk, jump, reach the flag!",
    "Altın Toplama": "Coin Collector",
    "Altınları topla, yıldız kazan": "Collect coins, earn stars",
    "Can Kalbi": "Life Heart",
    "Kalp: +1 can verir": "Hearts give +1 life",
    "Kırmızı Dost": "Red Buddy",
    "Düşmanın üstüne zıpla, yanına değme": "Stomp enemies, avoid their sides",
    "Boing!": "Boing!",
    "Yay: üstüne bas, yükseğe fırla": "Springs: step on them, fly high",
    "Çatlak Yol": "Cracked Path",
    "Çatlak taş basınca kırılır": "Cracked stones break underfoot",
    "Kanatlı Misafir": "Winged Guest",
    "Kayan Tahta": "Sliding Board",
    "Mavi platform seni taşır": "Blue platforms carry you",
    "Mıknatıs": "Magnet",
    "Mıknatıs altınları sana çeker": "Magnets pull coins to you",
    "Sümük Zıpzıp": "Bouncy Slime",
    "Sümük zıplar, inince üstüne bas": "Slimes hop, stomp them as they land",
    "Kalkan": "Shield",
    "Kalkan seni düşmandan korur": "Shields protect you from enemies",
    "Dikenli Dost": "Spiky Buddy",
    "Kirpiye BASMA, üstünden atla": "DON'T stomp hedgehogs, jump over",
    "Vızz Vızz": "Buzz Buzz",
    "Arı aşağı yukarı uçar": "Bees fly up and down",
    "Pat Pat": "Pop Pop",
    "Topçu ateş atar, üstüne zıpla": "Cannons shoot fire, jump on them",
    "Sıcak Ayaklar": "Hot Feet",
    "Lav geliyor ama yavaş": "Lava is coming, but slowly",
    "Karışık Torba": "Mixed Bag",
    "Hepsi bir arada!": "All together!",
    "Uzun Yol": "Long Road",
    "Bu sefer biraz uzun": "A bit longer this time",
    "Lavlı Tepe": "Lava Hill",
    "Lav yine geliyor, acele et": "Lava again, hurry up",
    "Yıldızlara Doğru": "To the Stars",
    "Küçük platformlar da var": "Small platforms too",
    "Büyük Tırmanış": "The Great Climb",
    "Son bölüm: zirveye çık!": "Last level: reach the summit!",
    "İlk Adımlar": "First Steps",
    "Platformlara zıpla, bayrağa ulaş!": "Jump on platforms, reach the flag!",
    "Kalp Avı": "Heart Hunt",
    "İlk Düşman": "First Enemy",
    "Zıpla Zıpla": "Jump Jump",
    "Lav Geliyor!": "Lava Is Coming!",
    "Lav yükseliyor, acele et!": "Lava is rising, hurry!",
    "Kayan Yollar": "Sliding Paths",
    "Gece Kanatları": "Night Wings",
    "Çatlak Taşlar": "Cracked Stones",
    "Çatlak taş kırılır, mıknatıs altın çeker": "Stones crack, magnets pull coins",
    "Yapışkan Sümük": "Sticky Slime",
    "Dikenli Yol": "Spiky Path",
    "Kirpiye BASMA! Kalkan seni korur": "DON'T stomp hedgehogs! Shields help",
    "Arı Kovanı": "Beehive",
    "Ateş Hattı": "Line of Fire",
    "Hepsi Bir Arada": "All in One",
    "Şimdi her şey bir arada!": "Now everything at once!",
    "Kızgın Kaçış": "Hot Escape",
    "Lav bu sefer daha hızlı!": "Lava is faster this time!",
    "Gök Merdiveni": "Sky Ladder",
    "Küçük platformlar geliyor": "Small platforms ahead",
    "Ateş Çemberi": "Ring of Fire",
    "Lav ve topçular bir arada": "Lava and cannons together",
    "Düşman Ordusu": "Enemy Army",
    "Her yer düşman dolu!": "Enemies everywhere!",
    "Lav Seli": "Lava Flood",
    "Durmak yok!": "No stopping!",
    "Son Hazırlık": "Final Prep",
    "Neredeyse zirvedesin": "You're almost at the top",
    "Zirve": "The Summit",
    "Isınma Turu": "Warm-Up Lap",
    "Zor bölümler başlıyor!": "The hard levels begin!",
    "Yay Kulesi": "Spring Tower",
    "Yaylarla göğe fırla": "Bounce to the sky on springs",
    "Kırık Köprüler": "Broken Bridges",
    "Çatlak taşlarda durma!": "Don't stop on cracked stones!",
    "Yarasa Mağarası": "Bat Cave",
    "Gökyüzü yarasa dolu": "The sky is full of bats",
    "Lav Kovalıyor": "Lava Chase",
    "Lav hemen peşinde!": "Lava is right behind you!",
    "Sümük Bataklığı": "Slime Swamp",
    "Her yerde zıplayan sümük": "Hopping slimes everywhere",
    "Kayan Kule": "Sliding Tower",
    "Hareketli platformlar": "Moving platforms",
    "Diken Tarlası": "Spike Field",
    "Kirpilere dikkat!": "Watch out for hedgehogs!",
    "Arı Fırtınası": "Bee Storm",
    "Arılar her yerde": "Bees everywhere",
    "Topçu Kalesi": "Cannon Castle",
    "Ateş toplarından kaç": "Dodge the fireballs",
    "Gece Avı": "Night Hunt",
    "Uçanlar ve yürüyenler": "Fliers and walkers",
    "Sıcak Takip": "Hot Pursuit",
    "Lav daha da hızlı!": "Lava is even faster!",
    "Kırık Merdiven": "Broken Stairs",
    "Çatlak taş ve lav": "Cracked stones and lava",
    "Kalabalık": "Crowded",
    "Düşman ordusu!": "An enemy army!",
    "Yaylı Kaçış": "Spring Escape",
    "Yaylara bas, lavdan kaç": "Use springs, escape the lava",
    "Karanlık Gök": "Dark Sky",
    "Küçük platformlar, çok düşman": "Small platforms, many enemies",
    "Dikenli Kale": "Spiky Fortress",
    "Kirpiler ve topçular": "Hedgehogs and cannons",
    "Lav Nehri": "Lava River",
    "Durursan yanarsın!": "Stop and you burn!",
    "Son Sınav": "Final Test",
    "Neredeyse bitti": "Almost done",
    "Dev Zirve": "Giant Summit",
    "Son bölüm: en yükseğe!": "Last level: to the very top!",
    "Tek Can": "One Life",
    "Tek canın var, dikkat!": "Only one life, be careful!",
    "Hızlı Lav": "Fast Lava",
    "Lav beklemiyor!": "Lava won't wait!",
    "Yay Çılgınlığı": "Spring Madness",
    "Yaylarla uç": "Fly on springs",
    "Çökük Yol": "Collapsing Road",
    "Basınca kırılan taşlar": "Stones that break underfoot",
    "Gece Sürüsü": "Night Swarm",
    "Yarasa sürüsü": "A swarm of bats",
    "Topçu Hattı": "Cannon Line",
    "Ateş topları ve lav": "Fireballs and lava",
    "Sümük Yağmuru": "Slime Rain",
    "Sümükler zıplıyor": "Slimes are hopping",
    "Diken Duvarı": "Spike Wall",
    "Kirpi dolu platformlar": "Platforms full of hedgehogs",
    "Arı Sürüsü": "Bee Swarm",
    "Arılar yolunu kesiyor": "Bees block your way",
    "Kayan Tuzak": "Sliding Trap",
    "Hareketli platform ve lav": "Moving platforms and lava",
    "Kaos": "Chaos",
    "Her yer düşman!": "Enemies all around!",
    "Ateş Yağmuru": "Fire Rain",
    "Topçular ve hızlı lav": "Cannons and fast lava",
    "Kırık Kule": "Broken Tower",
    "Kırılan taşlar, beklemeyen lav": "Breaking stones, impatient lava",
    "Uçan Ordu": "Flying Army",
    "Gökyüzü düşman dolu": "The sky is full of enemies",
    "Durma!": "Don't Stop!",
    "Lav çok hızlı!": "Lava is very fast!",
    "Kâbus": "Nightmare",
    "Her şey bir arada": "Everything at once",
    "Çılgın Tırmanış": "Crazy Climb",
    "Hızlı ve uzun": "Fast and long",
    "Lav Okyanusu": "Lava Ocean",
    "Lav seni yutmak istiyor": "The lava wants to swallow you",
    "Efsane": "Legend",
    "Sadece efsaneler geçer": "Only legends make it",
    "Ultra Zirve": "Ultra Summit",
    "Son bölüm: başarabilir misin?": "Last level: can you make it?",
}
